id: asdf://astropy.org/photutils/manifests/photutils-1.0.0
extension_uri: asdf://astropy.org/photutils/extensions/photutils-1.0.0
title: Photutils extension 1.0.0
description: |-
  A set of tags for serializing photutils objects.
tags:
- tag_uri: tag:astropy.org:photutils/aperture/circular_aperture-1.0.0
  schema_uri: asdf://astropy.org/photutils/schemas/aperture/circular_aperture-1.0.0
  title: CircularAperture 
  description: Circular aperture with one or more positions.
- tag_uri: tag:astropy.org:photutils/psf/airy_disk_psf-1.0.0
  schema_uri: asdf://astropy.org/photutils/schemas/psf/airy_disk_psf-1.0.0
  title: AiryDiskPSF
  description: ASDF schema for serializing a photutils AiryDiskPSF.
