id: asdf://astropy.org/photutils/manifests/photutils-1.0.0
extension_uri: asdf://astropy.org/photutils/extensions/photutils-1.0.0
title: Photutils extension 1.0.0
description: |-
  A set of tags for serializing photutils objects.
tags:
  - tag_uri: tag:astropy.org:photutils/aperture/circular_aperture-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/aperture/circular_aperture-1.0.0
    title: Circular aperture
    description: A circular aperture in pixel or sky coordinates.
  - tag_uri: tag:astropy.org:photutils/aperture/circular_annulus-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/aperture/circular_annulus-1.0.0
    title: Circular annulus aperture
    description: A circular annulus aperture in pixel or sky coordinates.
  - tag_uri: tag:astropy.org:photutils/aperture/elliptical_aperture-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/aperture/elliptical_aperture-1.0.0
    title: Elliptical aperture
    description: An elliptical aperture in pixel or sky coordinates.
  - tag_uri: tag:astropy.org:photutils/aperture/elliptical_annulus-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/aperture/elliptical_annulus-1.0.0
    title: Elliptical annulus aperture
    description: An elliptical annulus aperture in pixel or sky coordinates.
  - tag_uri: tag:astropy.org:photutils/aperture/polygon_aperture-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/aperture/polygon_aperture-1.0.0
    title: Polygon aperture
    description: A polygon aperture in pixel or sky coordinates.
  - tag_uri: tag:astropy.org:photutils/aperture/rectangular_aperture-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/aperture/rectangular_aperture-1.0.0
    title: Rectangular aperture
    description: A rectangular aperture in pixel or sky coordinates.
  - tag_uri: tag:astropy.org:photutils/aperture/rectangular_annulus-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/aperture/rectangular_annulus-1.0.0
    title: Rectangular annulus aperture
    description: A rectangular annulus aperture in pixel or sky coordinates.
  - tag_uri: tag:astropy.org:photutils/psf/airy_disk_psf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/airy_disk_psf-1.0.0
    title: AiryDiskPSF
    description: A 2D Airy disk PSF model.
  - tag_uri: tag:astropy.org:photutils/psf/circular_gaussian_prf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/circular_gaussian_prf-1.0.0
    title: CircularGaussianPRF
    description: A circular 2D Gaussian PRF model.
  - tag_uri: tag:astropy.org:photutils/psf/circular_gaussian_psf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/circular_gaussian_psf-1.0.0
    title: CircularGaussianPSF
    description: A circular 2D Gaussian PSF model.
  - tag_uri: tag:astropy.org:photutils/psf/circular_gaussian_sigma_prf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/circular_gaussian_sigma_prf-1.0.0
    title: CircularGaussianSigmaPRF
    description: A circular 2D Gaussian PRF model parameterized by sigma.
  - tag_uri: tag:astropy.org:photutils/psf/gaussian_prf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/gaussian_prf-1.0.0
    title: GaussianPRF
    description: A 2D Gaussian PRF model.
  - tag_uri: tag:astropy.org:photutils/psf/gaussian_psf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/gaussian_psf-1.0.0
    title: GaussianPSF
    description: A 2D Gaussian PSF model.
  - tag_uri: tag:astropy.org:photutils/psf/gridded_psf_model-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/gridded_psf_model-1.0.0
    title: GriddedPSFModel
    description: A grid of 2D ePSF models.
  - tag_uri: tag:astropy.org:photutils/psf/image_psf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/image_psf-1.0.0
    title: ImagePSF
    description: A 2D image PSF model.
  - tag_uri: tag:astropy.org:photutils/psf/moffat_psf-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/moffat_psf-1.0.0
    title: MoffatPSF
    description: A 2D Moffat PSF model.
  - tag_uri: tag:astropy.org:photutils/psf/stdpsf_grid-1.0.0
    schema_uri: asdf://astropy.org/photutils/schemas/psf/stdpsf_grid-1.0.0
    title: STDPSFGrid
    description: A grid of 2D ePSF models in the STDPSF format.
